---
dist: trusty

env:
  global:
    - user_cert: c:\projects\ansible-harden-windows\user.pem
    - user_key: c:\projects\ansible-harden-windows\key.pem
    - user_pfx: c:\projects\ansible-harden-windows\user.pfx

matrix:
  include:

    - os: linux
      language: python
      python: "2.7"
      before_install:
        - ln -s ansible-harden-windows ../juju4.harden-windows
      install:
        - sudo apt-get install libxml2-utils
        - pip install ansible ansible-lint
        - ansible --version
        - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
        - "echo \"[test-kitchen]\nlocalhost\" > inventory"
        - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
      script:
        - "ansible-lint tasks/main.yml"
        # Check the role/playbook's syntax.
        - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"

    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.7.0
          ANSIBLE_EXTRA_VARS:
          SUITE: default
    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.6.5
          ANSIBLE_EXTRA_VARS:
          SUITE: default
    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.5.10
          ANSIBLE_EXTRA_VARS:
          SUITE: default
    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.7.0
          ANSIBLE_EXTRA_VARS:
          SUITE: full

      before_install:
        - bash -c 'echo $BASH_VERSION'
        - df -h
        - wslconfig /list
        - wsl pwd
        # setup winrm
        - net user /Y /add $env:winrm_user $env:winrm_password
        - net localgroup administrators $env:winrm_user /add
        - set
        - powershell.exe -File test\appveyor\create_cert.ps1
        - winrm set winrm/config/client/auth '@{Basic="true"}'
        - winrm set winrm/config/service/auth '@{Basic="true"}'
        - winrm set winrm/config/service/auth '@{Certificate="true"}'
        - winrm set winrm/config/service/auth '@{CbtHardeningLevel="Strict"}'
        - winrm set winrm/config/service '@{AllowUnencrypted="true"}'
        - powershell -Command "Write-Host $env:PATH"
        - powershell -Command "($pwd).path"

      install:
        # setup environment
        - wsl sudo apt-get update
        - wsl sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y python sudo python-pip python-dev libffi-dev python-apt aptitude libssl-dev
        # setup ansible
        - wsl uname -a
        - wsl sudo pip install --upgrade pip
        - wsl sudo pip install ansible==$ANSIBLE_VERSION
        - wsl ansible --version
        - wsl echo localhost ansible_user=$winrm_user ansible_password=$winrm_password ansible_connection=winrm
        - wsl ls /
        - wsl ansible -i /mnt/c/projects/ansible-harden-windows/test/appveyor/inventory -m win_ping -vvv localhost'"
        - wsl mkdir -p /etc/ansible/roles
        - wsl cp /mnt/c/projects/ansible-harden-windows/test/appveyor/ansible.cfg /etc/ansible
        - wsl cp -R /mnt/c/projects/ansible-harden-windows /etc/ansible/roles/juju4.harden-windows
        - wsl sh -x /mnt/c/projects/ansible-harden-windows/get-dependencies.sh

      script:
        - wsl ansible-playbook /mnt/c/projects/ansible-harden-windows/test/integration/$SUITE/default.yml --syntax-check
        - wsl ansible-playbook -i /mnt/c/projects/ansible-harden-windows/test/appveyor/inventory /mnt/c/projects/ansible-harden-windows/test/integration/$SUITE/default.yml -vvv $ANSIBLE_EXTRA_VARS

      after_failure:
        - powershell -Command "Get-WinEvent -LogName 'Microsoft-Windows-AppLocker/EXE and DLL' | Where { $_.ID -eq 8004 }"
        - wsl ansible -i /mnt/c/projects/ansible-harden-windows/test/appveyor/inventory -m setup -vvv localhost

      after_script:
        - powershell -Command 'Get-ChildItem -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.hta" -Recurse'
        - powershell -Command 'Get-ChildItem -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList"'
        - c:\opscode\inspec\bin\inspec.bat exec https://github.com/juju4/windows-baseline/ || exit 0
