---
dist: trusty

env:
  global:
    - winrm_user: winrm_test_user
    - winrm_password: WinRM_test_Pass@w0rd1
    - user_cert: c:\projects\ansible-harden-windows\user.pem
    - user_key: c:\projects\ansible-harden-windows\key.pem
    - user_pfx: c:\projects\ansible-harden-windows\user.pfx

matrix:
  include:

    - os: linux
      language: python
      python: "2.7"
      before_install:
        - ln -s ansible-harden-windows ../juju4.harden-windows
      install:
        - sudo apt-get install libxml2-utils
        - pip install ansible ansible-lint
        - ansible --version
        - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
        - "echo \"[test-kitchen]\nlocalhost\" > inventory"
        - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
      script:
        - "ansible-lint tasks/main.yml"
        # Check the role/playbook's syntax.
        - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"

    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.7.0
          ANSIBLE_EXTRA_VARS:
          SUITE: default
    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.6.5
          ANSIBLE_EXTRA_VARS:
          SUITE: default
    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.5.10
          ANSIBLE_EXTRA_VARS:
          SUITE: default
    - os: windows
      language: shell
      env:
        - ANSIBLE_VERSION: 2.7.0
          ANSIBLE_EXTRA_VARS:
          SUITE: full

      before_install:
        - bash -c 'echo $BASH_VERSION'
        - df -h
        - curl -L -o ubuntu-1804.zip https://aka.ms/wsl-ubuntu-1804
        - powershell.exe -NoProfile -Command "Expand-Archive -Path ubuntu-1804.zip -DestinationPath Ubuntu"
        - Ubuntu/ubuntu1804.exe install --root
#        - wslconfig /list
        - wsl pwd
        # setup winrm
#        - net user /Y /add %winrm_user% %winrm_password%
#        - net localgroup administrators %winrm_user% /add
        - set
        - wsl find || true
        - powershell.exe -ExecutionPolicy Bypass -File test/appveyor/create_cert.ps1
        - powershell -Command "Test-WSMan -Authentication default"
        - powershell -Command "Get-PSSessionConfiguration"
        - powershell -Command "Get-Item WSMan:\localhost\Client\TrustedHosts"
        - powershell -Command "Get-ChildItem WSMan:\localhost\Client\DefaultPorts"
        - powershell -Command "Get-ChildItem WSMan:\localhost\Listener"
        - powershell -Command "Get-Service -Name winrm | Select Status"
#        - winrm set winrm/config/client/auth '@{Basic="true"}'
#        - winrm set winrm/config/service/auth '@{Basic="true"}'
#        - winrm set winrm/config/service/auth '@{Certificate="true"}'
#        - winrm set winrm/config/service/auth '@{CbtHardeningLevel="Strict"}'
#        - winrm set winrm/config/service '@{AllowUnencrypted="true"}'
        - powershell -Command "Write-Host $env:PATH"
#        - powershell -Command "($pwd).path"

      install:
        # setup environment
        - wsl sudo apt-get update
        - wsl sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y python3 sudo python3-pip python-dev libffi-dev python-apt aptitude libssl-dev
        # setup ansible
        - wsl uname -a
        - wsl sudo pip3 install --upgrade pip
        - wsl sudo pip3 install ansible==$ANSIBLE_VERSION
        - wsl ansible --version
        - wsl echo localhost ansible_user=%winrm_user% ansible_password=%winrm_password% ansible_connection=winrm
        - wsl ls /
        - wsl ansible -i /mnt/c/Users/travis/build/juju4/ansible-harden-windows/test/appveyor/inventory -m win_ping -vvv localhost'"
        - wsl mkdir -p /etc/ansible/roles
        - wsl cp /mnt/c/Users/travis/build/juju4/ansible-harden-windows/test/appveyor/ansible.cfg /etc/ansible
        - wsl cp -R /mnt/c/Users/travis/build/juju4/ansible-harden-windows /etc/ansible/roles/juju4.harden-windows
        - wsl sh -x /mnt/c/Users/travis/build/juju4/ansible-harden-windows/get-dependencies.sh

      script:
        - wsl ansible-playbook /mnt/c/Users/travis/build/juju4/ansible-harden-windows/test/integration/$SUITE/default.yml --syntax-check
        - wsl ansible-playbook -i /mnt/c/Users/travis/build/juju4/ansible-harden-windows/test/appveyor/inventory /mnt/c/Users/travis/build/juju4/ansible-harden-windows/test/integration/$SUITE/default.yml -vvv $ANSIBLE_EXTRA_VARS

      after_failure:
        - powershell -Command "Get-WinEvent -LogName 'Microsoft-Windows-AppLocker/EXE and DLL' | Where { $_.ID -eq 8004 }"
        - wsl ansible -i /mnt/c/Users/travis/build/juju4/ansible-harden-windows/test/appveyor/inventory -m setup -vvv localhost

      after_script:
        - powershell -Command 'Get-ChildItem -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.hta" -Recurse'
        - powershell -Command 'Get-ChildItem -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList"'
        - c:\opscode\inspec\bin\inspec.bat exec https://github.com/juju4/windows-baseline/ || exit 0
