---

- name: testing | download cert.at densityscout
  win_get_url:
          url: https://www.cert.at/media/files/downloads/software/densityscout/files/densityscout_build_45_windows.zip
    dest: "{{ harden_win_temp_dir }}\\densityscout.zip"
  ignore_errors: true
  register: densitydl
  register: dl_result
  until: dl_result is success

- name: testing | Unarchive densityscout
  win_unzip:
    src: "{{ harden_win_temp_dir }}\\densityscout.zip"
    dest: "{{ harden_win_temp_dir }}\\densityscout"
    creates: "{{ harden_win_temp_dir }}\\densityscout\\densityscout.exe"
  when: densitydl is succeeded

- name: testing | call densityscout
  win_command: >
    {{ harden_win_temp_dir }}\\densityscout\\densityscout.exe -pe -p 0.1 -o {{ harden_win_log_dir }}\\densityscout-results.txt c:\Windows
  ignore_errors: true
  when: densitydl is succeeded
