---

- set_fact:
    ansible_become_password: "_Password_CI_CD_to_be_revoked1_"

## FIXME! failing on second pass, https://groups.google.com/forum/#!topic/ansible-project/_ydkYXZibrM
- name: Ensure user _test is present
  win_user:
    name: _test2
    password: "{{ ansible_become_password }}"
    state: present
    groups:
      - Users

- name: try to use trivial passwords
  win_command: "net user _test2 {{ item }}"
  with_items:
    - passwd
    - 123123123
    - iloveyou
    - dragon123456
  ignore_errors: true
  register: opftest
  failed_when: "'The command completed successfully.' in opftest.stdout"

- name: Remove user _test
  win_user:
    name: _test2
    state: absent

