---

# https://twitter.com/GossiTheDog/status/932694287480913920
- name: Download test office files
  win_get_url:
    url: "{{ item }}"
    dest: "{{ harden_win_temp_dir }}\\{{ item | win_basename }}"
  with_items:
    - http://owned.lab6.com/~gossi/research/public/cve-2017-11882/calc.doc
    - http://owned.lab6.com/~gossi/research/public/cve-2017-11882/test.doc

- name: MsOffice trial by Chocolatey installation
  win_chocolatey:
    name: "{{ item }}"
    state: present
    upgrade: no
  with_items:
# 2013
#    - officeproplus2013
# 2016
    - office365business
#    - office365proplus
#    - office365homepremium
#    - microsoft-teams
