---
## Only domain joined station
## https://blogs.technet.microsoft.com/askpfeplat/2015/12/28/local-administrator-password-solution-laps-implementation-hints-and-security-nerd-commentary-including-mini-threat-model/
## https://adsecurity.org/?p=1790
## https://adsecurity.org/?p=3164
#PS> Get-ADComputer -Filter {ms-McsAdmPwdExpirationTime -Like “*”} -Property ms-McsAdmPwdExpirationTime
## https://flamingkeys.com/deploying-the-local-administrator-password-solution-part-1/
## https://blogs.technet.microsoft.com/kfalde/2015/11/18/laps-audit-reporting-via-wef-posh-and-powerbi/
## https://github.com/kurtfalde/LAPS-Reporting
## https://blog.netspi.com/running-laps-around-cleartext-passwords/
## https://github.com/kfosaaen/Get-LAPSPasswords
#PS> Get-ADObject 'CN=ms-mcs-admpwd,CN=Schema,CN=Configuration,DC=mydomain,DC=com'
#PS> Find-AdmPwdExtendedrights
#PS> Get-AdmPwdPassword -ComputerName <computername>
#PS> Get-LAPSPasswords -DomainController 192.168.1.1 -Credential DEMO\karl | Format-Table -AutoSize
#PS> Get-ADComputer -Filter * -Property * | Format-Table Name,OperatingSystem,OperatingSystemServicePack,OperatingSystemVersion -Wrap Auto
#PS> Get-ADComputer -Filter {OperatingSystem -Like “Windows Server*”} -Property * | Format-Table Name,OperatingSystem,OperatingSystemServicePack -Wrap -Auto | Export-CSV AllWindows.csv -NoTypeInformation -Encoding UTF8
## Audit with Configuration Manager: https://4sysops.com/archives/monitoring-laps-with-configuration-manager/
## https://room362.com/post/2017/dump-laps-passwords-with-ldapsearch/
## http://archive.hack.lu/2017/HackLU_2017_Malicious_use_LAPS_Clementz_Goichot.pdf

## https://www.microsoft.com/en-us/download/details.aspx?id=46899
- name: Download LAPS
  win_get_url:
    url: 'https://download.microsoft.com/download/C/7/A/C7AAD914-A8A6-4904-88A1-29E657445D03/LAPS.x64.msi'
    dest: "{{ harden_win_temp_dir }}\\LAPS.x64.msi"

- name: Install LAPS - targeted computer
  win_package:
    path: "{{ harden_win_temp_dir }}\\LAPS.x64.msi"
    wait: true
# To hide software in Programs and Features Control panel view, use msiexec parameter ARPSYSTEMCOMPONENT=1:
    extra_args: '/quiet /qn ARPSYSTEMCOMPONENT=1'
- name: DC | Install LAPS
  win_package:
    path: "{{ harden_win_temp_dir }}\\LAPS.x64.msi"
    wait: true
# silent install of CSE and all management tools
    extra_args: '/qn ADDLOCAL=CSE,Management,Management.UI,Management.PS,Management.ADMX'

- name: DC | add LAPS to AD schema
  win_shell: "{{ item }}"
  with_items:
    - Import-Module AdmPwd.PS
    - Update-AdmPwdADSchema
# Auditing
#    - Set-AdmPwdAuditing -OrgUnit $OU-of-Computers-to-Audit -AuditedPrincipals:$Group-to-Audit
  when: harden_win_laps_dc

## https://4sysops.com/archives/part-2-faqs-for-microsoft-local-administrator-password-solution-laps/
## 0 (the default) to log errors only, 1 to log errors and warnings, and 2 for verbose logging.
- name: Enable Errors and Warning logging
  win_regedit:
    key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\GPExtensions\{D76B9641-3288-4f75-942D-087DE603E3EA}'
    value: ExtensionDebugLevel
    data: 2
    datatype: dword
