---

- name: Firewall | add rule for {{ program }}
  win_firewall_rule:
    name: "{{ harden_win_fw_prefix }}-{{ action }}-{{ direction }}-{{ program | win_basename }}-{{ item }}"
    program: "{{ program }}"
    enable: yes
    state: present
    action: "{{ action }}"
    direction: "{{ direction }}"
    profile: "{{ profile }}"
  with_items: "{{ harden_win_fw_web_ports }}"
