---

- name: Disable Remote Desktop
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
    value: fDenyTSConnections
    data: 1
    datatype: dword
  when: not harden_win_rdp_enable

- name: Enforce Secure RDP connection (default ws2016)
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
    value: UserAuthentication
    data: 1
    datatype: dword

- name: Enforce Secure RDP connection
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
    value: MinEncryptionLevel
    data: "{{ harden_win_rdp_encryptionlevel }}"
    datatype: dword

- include: windows-rdp-restricted.yml
