---
## https://support.microsoft.com/en-us/help/929852/how-to-disable-ipv6-or-its-components-in-windows
## https://techjourney.net/how-to-disable-tcpipv6-teredo-tunneling-in-windows/
## https://technet.microsoft.com/en-us/library/2009.07.cableguy.aspx
## https://insinuator.net/2017/01/ipv6-properties-of-windows-server-2016-windows-10/
## https://blogs.msdn.microsoft.com/virtual_pc_guy/2014/03/25/hyper-v-networkingrouter-guard/
## https://blogs.technet.microsoft.com/askpfeplat/2013/06/16/ipv6-for-the-windows-administrator-why-you-need-to-care-about-ipv6/

## https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1803-removed-features
## "6to4 has been disabled by default since Windows 10, version 1607 (the Anniversary Update), ISATAP has been disabled by default since Windows 10, version 1703 (the Creators Update), and Direct Tunnels has always been disabled by default. Please use native IPv6 support instead."
- name: Disable Non-native IPv6 (Tunnels)
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    name: DisabledComponents
    data: 14
    type: dword
